[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
via-ir = true
optimizer_runs = 1
evm_version = "cancun"
metadata = true
metadata_hash = "ipfs"
use_literal_content = true # use source code

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz_runs = 1000

# Base Configuration
eth-rpc-url = "https://sepolia.base.org"
chain_id = 84532

# See more config options https://github.com/foundry-rs/foundry/blob/master/cra$