[profile.default]
auto_detect_solc = false
solc = "0.8.30"

src = "src"
test = "test"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200
via_ir = true                     # IMPORTANT - enable IR to avoid "stack too deep" in complex files
bytecode_hash = "ipfs"             # IMPORTANT
evm_version = "cancun"              # required for newer OZ Bytes.mcopy
use_literal_content = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

eth-rpc-url = "https://sepolia.base.org"
chain_id = 84532
