[profile.default]
auto_detect_solc = false
solc = "0.8.30"

src = "src"
test = "test"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200
via_ir = false                     # IMPORTANT
bytecode_hash = "ipfs"             # IMPORTANT
evm_version = "paris"              # safest for Base
use_literal_content = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

eth-rpc-url = "https://sepolia.base.org"
chain_id = 84532
